# Generated by Django 4.2.3 on 2023-07-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_classsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classes_sections',
            field=models.ManyToManyField(related_name='students', to='school_app.classsection'),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classsection',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
